.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DEVICES.CSV 5 "May 08, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME

Configuration files for network devices:

default-school:
.br
/etc/linuxmuster/sophomorix/default-school/devices.csv

Other <school>:
.br
/etc/linuxmuster/sophomorix/<school>/<school>.devices.csv

.br
.SH DESCRIPTION
This data is used to configure various services (DHCP, DNS, Linbo etc.) by
processing them through the linuxmuster-import-devices script.

As part of this processing, sophomorix-device takes care of the entries in the
Active Directory of Samba 4 (DNS, computer accounts, groups etc.)

.PP
.SH FIELDS

The following 15 fields have to be on one row separated by semicolons:
.TP
.B Field 1: room name
.br
creates a group with sophomorixType 'room'
.TP
.B Field 2: hostname
.br
creates a dnsNode and (depending on sophomorixRole) a computer
account and a printer group (if sophomorixRole is printer).
.TP
.B Field 3: device group (formerly known as hardwareclass)
.br
created as sophomorixType 'hardwareclass'
.TP
.B Field 4: mac address
.TP
.B Field 5: client ip (IPv4)
.TP
.B Field 6: ms office key
.TP
.B Field 7: ms windows key
.TP
.B Field 8: supplemental dhcp options, comma separated
.TP
.B Field 9: sophomorixRole
.br
Only certain rolenames are valid.
.TP
.B Field 10: reserved by linuxmuster.net
.TP
.B Field 11: pxe flag
.br
Possible values 0-3:
.br
0: no pxe, 1: linbo pxe, 2: linbo pxe + opsi mgmt, 3: opsi pxe
.TP
.B Field 12: reserved by linuxmuster.net
.TP
.B Field 13: reserved by linuxmuster.net
.TP
.B Field 14: reserved by linuxmuster.net
.TP
.B Field 15: sophomorixComment
.br
comment field sophomorixComment for computer account.

.SH Notes:

.B room name
.br
Apart from the 'default-school', room names are given a prefix: '<school>-<room>'.

.B hostname
.br
Apart from the 'default-school', dnsNode names and computer accounts are given
a prefix: '<school>-<hostname>'.

Computer account names consist of capital letters followed by $:
hostname 'a102pc1' will be dnsNode 'a102pc1' and computer
account 'A102PC1$'.

.B device groups (hardwareclass)
.br
do NOT get a prefix. They are globally valid.

.B sophomorixRole
.br
There are only predefined values, see

sophomorix-samba --show-roletype

sophomorixRole determines, whether a computer account will be created or not.

.B Other fields ...
.br
Further fields after position 16 are allowed and can be synchronized to AD by
configuration in the future.


.SH SEE ALSO
.BR sophomorix-device (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the programs by calling for example
.\".IR "sophomrix-useradd -h" ,
.
.SH AUTHOR
Written by <jeffbeck@web.de>, translated and amended by <thomas@linuxmuster.net>.
